//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMST.Storage.Client.Proxy.AccountServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignType", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.Account")]
    [System.SerializableAttribute()]
    public partial class SignType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignTypeID {
            get {
                return this.SignTypeIDField;
            }
            set {
                if ((this.SignTypeIDField.Equals(value) != true)) {
                    this.SignTypeIDField = value;
                    this.RaisePropertyChanged("SignTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignTypeName {
            get {
                return this.SignTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SignTypeNameField, value) != true)) {
                    this.SignTypeNameField = value;
                    this.RaisePropertyChanged("SignTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountServiceProxy.IAccountProxy")]
    public interface IAccountProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/QueryAvaliabeleStockStorageInfo", ReplyAction="http://tempuri.org/IAccount/QueryAvaliabeleStockStorageInfoResponse")]
        string QueryAvaliabeleStockStorageInfo(System.Nullable<int> company, System.Nullable<int> galId, string productName, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/QueryAvaliabeleStockStorageInfo", ReplyAction="http://tempuri.org/IAccount/QueryAvaliabeleStockStorageInfoResponse")]
        System.Threading.Tasks.Task<string> QueryAvaliabeleStockStorageInfoAsync(System.Nullable<int> company, System.Nullable<int> galId, string productName, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GenerateSignTypeClass", ReplyAction="http://tempuri.org/IAccount/GenerateSignTypeClassResponse")]
        CMST.Storage.Client.Proxy.AccountServiceProxy.SignType GenerateSignTypeClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GenerateSignTypeClass", ReplyAction="http://tempuri.org/IAccount/GenerateSignTypeClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.AccountServiceProxy.SignType> GenerateSignTypeClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GetSignTypeCache", ReplyAction="http://tempuri.org/IAccount/GetSignTypeCacheResponse")]
        System.Data.DataSet GetSignTypeCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccount/GetSignTypeCache", ReplyAction="http://tempuri.org/IAccount/GetSignTypeCacheResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSignTypeCacheAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountProxyChannel : CMST.Storage.Client.Proxy.AccountServiceProxy.IAccountProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountProxyClient : System.ServiceModel.ClientBase<CMST.Storage.Client.Proxy.AccountServiceProxy.IAccountProxy>, CMST.Storage.Client.Proxy.AccountServiceProxy.IAccountProxy {
        
        public AccountProxyClient() {
        }
        
        public AccountProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string QueryAvaliabeleStockStorageInfo(System.Nullable<int> company, System.Nullable<int> galId, string productName, string queryFields, int page, int pageSize) {
            return base.Channel.QueryAvaliabeleStockStorageInfo(company, galId, productName, queryFields, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<string> QueryAvaliabeleStockStorageInfoAsync(System.Nullable<int> company, System.Nullable<int> galId, string productName, string queryFields, int page, int pageSize) {
            return base.Channel.QueryAvaliabeleStockStorageInfoAsync(company, galId, productName, queryFields, page, pageSize);
        }
        
        public CMST.Storage.Client.Proxy.AccountServiceProxy.SignType GenerateSignTypeClass() {
            return base.Channel.GenerateSignTypeClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.AccountServiceProxy.SignType> GenerateSignTypeClassAsync() {
            return base.Channel.GenerateSignTypeClassAsync();
        }
        
        public System.Data.DataSet GetSignTypeCache() {
            return base.Channel.GetSignTypeCache();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSignTypeCacheAsync() {
            return base.Channel.GetSignTypeCacheAsync();
        }
    }
}
