//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMST.Storage.Client.Proxy.CarManageProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarRegister", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.CarManage")]
    [System.SerializableAttribute()]
    public partial class CarRegister : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CarRegisterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CmstIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterDetail> CrdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreCheckNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreCheckTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreCheckerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreCrsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreCrsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreItyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreItyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreMakeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreMakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreMakerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNo {
            get {
                return this.BillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNoField, value) != true)) {
                    this.BillNoField = value;
                    this.RaisePropertyChanged("BillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarNo {
            get {
                return this.CarNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CarNoField, value) != true)) {
                    this.CarNoField = value;
                    this.RaisePropertyChanged("CarNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CarRegisterID {
            get {
                return this.CarRegisterIDField;
            }
            set {
                if ((this.CarRegisterIDField.Equals(value) != true)) {
                    this.CarRegisterIDField = value;
                    this.RaisePropertyChanged("CarRegisterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmstID {
            get {
                return this.CmstIDField;
            }
            set {
                if ((this.CmstIDField.Equals(value) != true)) {
                    this.CmstIDField = value;
                    this.RaisePropertyChanged("CmstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterDetail> Crds {
            get {
                return this.CrdsField;
            }
            set {
                if ((object.ReferenceEquals(this.CrdsField, value) != true)) {
                    this.CrdsField = value;
                    this.RaisePropertyChanged("Crds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreCheckName {
            get {
                return this.CreCheckNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreCheckNameField, value) != true)) {
                    this.CreCheckNameField = value;
                    this.RaisePropertyChanged("CreCheckName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreCheckTime {
            get {
                return this.CreCheckTimeField;
            }
            set {
                if ((this.CreCheckTimeField.Equals(value) != true)) {
                    this.CreCheckTimeField = value;
                    this.RaisePropertyChanged("CreCheckTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreChecker {
            get {
                return this.CreCheckerField;
            }
            set {
                if ((this.CreCheckerField.Equals(value) != true)) {
                    this.CreCheckerField = value;
                    this.RaisePropertyChanged("CreChecker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreCrsId {
            get {
                return this.CreCrsIdField;
            }
            set {
                if ((this.CreCrsIdField.Equals(value) != true)) {
                    this.CreCrsIdField = value;
                    this.RaisePropertyChanged("CreCrsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreCrsName {
            get {
                return this.CreCrsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreCrsNameField, value) != true)) {
                    this.CreCrsNameField = value;
                    this.RaisePropertyChanged("CreCrsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreItyId {
            get {
                return this.CreItyIdField;
            }
            set {
                if ((this.CreItyIdField.Equals(value) != true)) {
                    this.CreItyIdField = value;
                    this.RaisePropertyChanged("CreItyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreItyName {
            get {
                return this.CreItyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreItyNameField, value) != true)) {
                    this.CreItyNameField = value;
                    this.RaisePropertyChanged("CreItyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreMakeTime {
            get {
                return this.CreMakeTimeField;
            }
            set {
                if ((this.CreMakeTimeField.Equals(value) != true)) {
                    this.CreMakeTimeField = value;
                    this.RaisePropertyChanged("CreMakeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreMaker {
            get {
                return this.CreMakerField;
            }
            set {
                if ((this.CreMakerField.Equals(value) != true)) {
                    this.CreMakerField = value;
                    this.RaisePropertyChanged("CreMaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreMakerName {
            get {
                return this.CreMakerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreMakerNameField, value) != true)) {
                    this.CreMakerNameField = value;
                    this.RaisePropertyChanged("CreMakerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarRegisterDetail", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.CarManage")]
    [System.SerializableAttribute()]
    public partial class CarRegisterDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CarRegisterDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CarRegisterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CrdMakeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrdMakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrdMakerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrdRemarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillID {
            get {
                return this.BillIDField;
            }
            set {
                if ((this.BillIDField.Equals(value) != true)) {
                    this.BillIDField = value;
                    this.RaisePropertyChanged("BillID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillType {
            get {
                return this.BillTypeField;
            }
            set {
                if ((this.BillTypeField.Equals(value) != true)) {
                    this.BillTypeField = value;
                    this.RaisePropertyChanged("BillType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillTypeName {
            get {
                return this.BillTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BillTypeNameField, value) != true)) {
                    this.BillTypeNameField = value;
                    this.RaisePropertyChanged("BillTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CarRegisterDetailID {
            get {
                return this.CarRegisterDetailIDField;
            }
            set {
                if ((this.CarRegisterDetailIDField.Equals(value) != true)) {
                    this.CarRegisterDetailIDField = value;
                    this.RaisePropertyChanged("CarRegisterDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CarRegisterID {
            get {
                return this.CarRegisterIDField;
            }
            set {
                if ((this.CarRegisterIDField.Equals(value) != true)) {
                    this.CarRegisterIDField = value;
                    this.RaisePropertyChanged("CarRegisterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CrdMakeTime {
            get {
                return this.CrdMakeTimeField;
            }
            set {
                if ((this.CrdMakeTimeField.Equals(value) != true)) {
                    this.CrdMakeTimeField = value;
                    this.RaisePropertyChanged("CrdMakeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrdMaker {
            get {
                return this.CrdMakerField;
            }
            set {
                if ((this.CrdMakerField.Equals(value) != true)) {
                    this.CrdMakerField = value;
                    this.RaisePropertyChanged("CrdMaker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrdMakerName {
            get {
                return this.CrdMakerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CrdMakerNameField, value) != true)) {
                    this.CrdMakerNameField = value;
                    this.RaisePropertyChanged("CrdMakerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrdRemark {
            get {
                return this.CrdRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.CrdRemarkField, value) != true)) {
                    this.CrdRemarkField = value;
                    this.RaisePropertyChanged("CrdRemark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarRegisterQuery", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.CarManage")]
    [System.SerializableAttribute()]
    public partial class CarRegisterQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarBillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreCrsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cmstIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarBillNo {
            get {
                return this.CarBillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CarBillNoField, value) != true)) {
                    this.CarBillNoField = value;
                    this.RaisePropertyChanged("CarBillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreCrsId {
            get {
                return this.CreCrsIdField;
            }
            set {
                if ((this.CreCrsIdField.Equals(value) != true)) {
                    this.CreCrsIdField = value;
                    this.RaisePropertyChanged("CreCrsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeType {
            get {
                return this.TimeTypeField;
            }
            set {
                if ((this.TimeTypeField.Equals(value) != true)) {
                    this.TimeTypeField = value;
                    this.RaisePropertyChanged("TimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carNo {
            get {
                return this.carNoField;
            }
            set {
                if ((object.ReferenceEquals(this.carNoField, value) != true)) {
                    this.carNoField = value;
                    this.RaisePropertyChanged("carNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cmstId {
            get {
                return this.cmstIdField;
            }
            set {
                if ((this.cmstIdField.Equals(value) != true)) {
                    this.cmstIdField = value;
                    this.RaisePropertyChanged("cmstId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutStoreCheck", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.CarManage")]
    [System.SerializableAttribute()]
    public partial class OutStoreCheck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscCheckStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscCrdRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscGraNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscManNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OscOPlIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscOplRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscPacNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscPnaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscProNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OscSpeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AN {
            get {
                return this.ANField;
            }
            set {
                if ((this.ANField.Equals(value) != true)) {
                    this.ANField = value;
                    this.RaisePropertyChanged("AN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscCheckStatus {
            get {
                return this.OscCheckStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OscCheckStatusField, value) != true)) {
                    this.OscCheckStatusField = value;
                    this.RaisePropertyChanged("OscCheckStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscCrdRemark {
            get {
                return this.OscCrdRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.OscCrdRemarkField, value) != true)) {
                    this.OscCrdRemarkField = value;
                    this.RaisePropertyChanged("OscCrdRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscGraName {
            get {
                return this.OscGraNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OscGraNameField, value) != true)) {
                    this.OscGraNameField = value;
                    this.RaisePropertyChanged("OscGraName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscManName {
            get {
                return this.OscManNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OscManNameField, value) != true)) {
                    this.OscManNameField = value;
                    this.RaisePropertyChanged("OscManName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OscOPlId {
            get {
                return this.OscOPlIdField;
            }
            set {
                if ((this.OscOPlIdField.Equals(value) != true)) {
                    this.OscOPlIdField = value;
                    this.RaisePropertyChanged("OscOPlId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscOplRemark {
            get {
                return this.OscOplRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.OscOplRemarkField, value) != true)) {
                    this.OscOplRemarkField = value;
                    this.RaisePropertyChanged("OscOplRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscPacName {
            get {
                return this.OscPacNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OscPacNameField, value) != true)) {
                    this.OscPacNameField = value;
                    this.RaisePropertyChanged("OscPacName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscPnaName {
            get {
                return this.OscPnaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OscPnaNameField, value) != true)) {
                    this.OscPnaNameField = value;
                    this.RaisePropertyChanged("OscPnaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscProName {
            get {
                return this.OscProNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OscProNameField, value) != true)) {
                    this.OscProNameField = value;
                    this.RaisePropertyChanged("OscProName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OscSpeName {
            get {
                return this.OscSpeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OscSpeNameField, value) != true)) {
                    this.OscSpeNameField = value;
                    this.RaisePropertyChanged("OscSpeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PN {
            get {
                return this.PNField;
            }
            set {
                if ((this.PNField.Equals(value) != true)) {
                    this.PNField = value;
                    this.RaisePropertyChanged("PN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InStoreCheck", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.CarManage")]
    [System.SerializableAttribute()]
    public partial class InStoreCheck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscCrdRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscCreCarNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscGraNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IscIsbIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscIsbRemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscManNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscPacNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscPnaNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IscSpeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AN {
            get {
                return this.ANField;
            }
            set {
                if ((this.ANField.Equals(value) != true)) {
                    this.ANField = value;
                    this.RaisePropertyChanged("AN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscCrdRemark {
            get {
                return this.IscCrdRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.IscCrdRemarkField, value) != true)) {
                    this.IscCrdRemarkField = value;
                    this.RaisePropertyChanged("IscCrdRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscCreCarNo {
            get {
                return this.IscCreCarNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IscCreCarNoField, value) != true)) {
                    this.IscCreCarNoField = value;
                    this.RaisePropertyChanged("IscCreCarNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscGraName {
            get {
                return this.IscGraNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IscGraNameField, value) != true)) {
                    this.IscGraNameField = value;
                    this.RaisePropertyChanged("IscGraName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IscIsbId {
            get {
                return this.IscIsbIdField;
            }
            set {
                if ((this.IscIsbIdField.Equals(value) != true)) {
                    this.IscIsbIdField = value;
                    this.RaisePropertyChanged("IscIsbId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscIsbRemark {
            get {
                return this.IscIsbRemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.IscIsbRemarkField, value) != true)) {
                    this.IscIsbRemarkField = value;
                    this.RaisePropertyChanged("IscIsbRemark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscManName {
            get {
                return this.IscManNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IscManNameField, value) != true)) {
                    this.IscManNameField = value;
                    this.RaisePropertyChanged("IscManName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscPacName {
            get {
                return this.IscPacNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IscPacNameField, value) != true)) {
                    this.IscPacNameField = value;
                    this.RaisePropertyChanged("IscPacName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscPnaName {
            get {
                return this.IscPnaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IscPnaNameField, value) != true)) {
                    this.IscPnaNameField = value;
                    this.RaisePropertyChanged("IscPnaName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IscSpeName {
            get {
                return this.IscSpeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IscSpeNameField, value) != true)) {
                    this.IscSpeNameField = value;
                    this.RaisePropertyChanged("IscSpeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PN {
            get {
                return this.PNField;
            }
            set {
                if ((this.PNField.Equals(value) != true)) {
                    this.PNField = value;
                    this.RaisePropertyChanged("PN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarManageProxy.ICarManageProxy")]
    public interface ICarManageProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/SaveCarRegister", ReplyAction="http://tempuri.org/ICarManage/SaveCarRegisterResponse")]
        string SaveCarRegister(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister cr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/SaveCarRegister", ReplyAction="http://tempuri.org/ICarManage/SaveCarRegisterResponse")]
        System.Threading.Tasks.Task<string> SaveCarRegisterAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister cr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/BindCarRegisterWithBill", ReplyAction="http://tempuri.org/ICarManage/BindCarRegisterWithBillResponse")]
        string BindCarRegisterWithBill(string BillNo, CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterDetail crd, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/BindCarRegisterWithBill", ReplyAction="http://tempuri.org/ICarManage/BindCarRegisterWithBillResponse")]
        System.Threading.Tasks.Task<string> BindCarRegisterWithBillAsync(string BillNo, CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterDetail crd, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterById", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByIdResponse")]
        string QueryCarRegisterById(long creId, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterById", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByIdResponse")]
        System.Threading.Tasks.Task<string> QueryCarRegisterByIdAsync(long creId, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterByBillNo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByBillNoResponse")]
        string QueryCarRegisterByBillNo(string BillNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterByBillNo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByBillNoResponse")]
        System.Threading.Tasks.Task<string> QueryCarRegisterByBillNoAsync(string BillNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterByCarNo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByCarNoResponse")]
        string QueryCarRegisterByCarNo(string carNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterByCarNo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByCarNoResponse")]
        System.Threading.Tasks.Task<string> QueryCarRegisterByCarNoAsync(string carNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterPageInfo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterPageInfoResponse")]
        string QueryCarRegisterPageInfo(CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterQuery crq, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterPageInfo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterPageInfoResponse")]
        System.Threading.Tasks.Task<string> QueryCarRegisterPageInfoAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterQuery crq, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryOutPlanByCarRegisterNo", ReplyAction="http://tempuri.org/ICarManage/QueryOutPlanByCarRegisterNoResponse")]
        string QueryOutPlanByCarRegisterNo(string CarRegisterNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryOutPlanByCarRegisterNo", ReplyAction="http://tempuri.org/ICarManage/QueryOutPlanByCarRegisterNoResponse")]
        System.Threading.Tasks.Task<string> QueryOutPlanByCarRegisterNoAsync(string CarRegisterNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryInStoreBillByCarRegisterNo", ReplyAction="http://tempuri.org/ICarManage/QueryInStoreBillByCarRegisterNoResponse")]
        string QueryInStoreBillByCarRegisterNo(string CarRegisterNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryInStoreBillByCarRegisterNo", ReplyAction="http://tempuri.org/ICarManage/QueryInStoreBillByCarRegisterNoResponse")]
        System.Threading.Tasks.Task<string> QueryInStoreBillByCarRegisterNoAsync(string CarRegisterNo, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/CheckCarRegister", ReplyAction="http://tempuri.org/ICarManage/CheckCarRegisterResponse")]
        string CheckCarRegister(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/CheckCarRegister", ReplyAction="http://tempuri.org/ICarManage/CheckCarRegisterResponse")]
        System.Threading.Tasks.Task<string> CheckCarRegisterAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryAllCarRegister", ReplyAction="http://tempuri.org/ICarManage/QueryAllCarRegisterResponse")]
        string QueryAllCarRegister(int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryAllCarRegister", ReplyAction="http://tempuri.org/ICarManage/QueryAllCarRegisterResponse")]
        System.Threading.Tasks.Task<string> QueryAllCarRegisterAsync(int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryAllCarRegisterId", ReplyAction="http://tempuri.org/ICarManage/QueryAllCarRegisterIdResponse")]
        string QueryAllCarRegisterId(int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryAllCarRegisterId", ReplyAction="http://tempuri.org/ICarManage/QueryAllCarRegisterIdResponse")]
        System.Threading.Tasks.Task<string> QueryAllCarRegisterIdAsync(int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterByCarNum", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByCarNumResponse")]
        string QueryCarRegisterByCarNum(string carNum, int carType, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterByCarNum", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterByCarNumResponse")]
        System.Threading.Tasks.Task<string> QueryCarRegisterByCarNumAsync(string carNum, int carType, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterDetailCountByBillNo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterDetailCountByBillNoResponse")]
        string QueryCarRegisterDetailCountByBillNo(long crdBillNo, int Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegisterDetailCountByBillNo", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegisterDetailCountByBillNoResponse")]
        System.Threading.Tasks.Task<string> QueryCarRegisterDetailCountByBillNoAsync(long crdBillNo, int Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegistersByBillNoAndBillType", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegistersByBillNoAndBillTypeResponse")]
        string QueryCarRegistersByBillNoAndBillType(long billNo, int billType, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/QueryCarRegistersByBillNoAndBillType", ReplyAction="http://tempuri.org/ICarManage/QueryCarRegistersByBillNoAndBillTypeResponse")]
        System.Threading.Tasks.Task<string> QueryCarRegistersByBillNoAndBillTypeAsync(long billNo, int billType, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/UnBindCarRegisterWithBill", ReplyAction="http://tempuri.org/ICarManage/UnBindCarRegisterWithBillResponse")]
        string UnBindCarRegisterWithBill(long BillNo, long carRegisterId, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/UnBindCarRegisterWithBill", ReplyAction="http://tempuri.org/ICarManage/UnBindCarRegisterWithBillResponse")]
        System.Threading.Tasks.Task<string> UnBindCarRegisterWithBillAsync(long BillNo, long carRegisterId, int cmstId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/GenerateCarRegisterClass", ReplyAction="http://tempuri.org/ICarManage/GenerateCarRegisterClassResponse")]
        CMST.Storage.Client.Proxy.CarManageProxy.CarRegister GenerateCarRegisterClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/GenerateCarRegisterClass", ReplyAction="http://tempuri.org/ICarManage/GenerateCarRegisterClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.CarManageProxy.CarRegister> GenerateCarRegisterClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/GenerateOutStoreCheckClass", ReplyAction="http://tempuri.org/ICarManage/GenerateOutStoreCheckClassResponse")]
        CMST.Storage.Client.Proxy.CarManageProxy.OutStoreCheck GenerateOutStoreCheckClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/GenerateOutStoreCheckClass", ReplyAction="http://tempuri.org/ICarManage/GenerateOutStoreCheckClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.CarManageProxy.OutStoreCheck> GenerateOutStoreCheckClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/GenerateInStoreCheckClass", ReplyAction="http://tempuri.org/ICarManage/GenerateInStoreCheckClassResponse")]
        CMST.Storage.Client.Proxy.CarManageProxy.InStoreCheck GenerateInStoreCheckClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/GenerateInStoreCheckClass", ReplyAction="http://tempuri.org/ICarManage/GenerateInStoreCheckClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.CarManageProxy.InStoreCheck> GenerateInStoreCheckClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/UpdateRemakeByCreID", ReplyAction="http://tempuri.org/ICarManage/UpdateRemakeByCreIDResponse")]
        string UpdateRemakeByCreID(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarManage/UpdateRemakeByCreID", ReplyAction="http://tempuri.org/ICarManage/UpdateRemakeByCreIDResponse")]
        System.Threading.Tasks.Task<string> UpdateRemakeByCreIDAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarManageProxyChannel : CMST.Storage.Client.Proxy.CarManageProxy.ICarManageProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarManageProxyClient : System.ServiceModel.ClientBase<CMST.Storage.Client.Proxy.CarManageProxy.ICarManageProxy>, CMST.Storage.Client.Proxy.CarManageProxy.ICarManageProxy {
        
        public CarManageProxyClient() {
        }
        
        public CarManageProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarManageProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarManageProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarManageProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveCarRegister(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister cr) {
            return base.Channel.SaveCarRegister(cr);
        }
        
        public System.Threading.Tasks.Task<string> SaveCarRegisterAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister cr) {
            return base.Channel.SaveCarRegisterAsync(cr);
        }
        
        public string BindCarRegisterWithBill(string BillNo, CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterDetail crd, int cmstId) {
            return base.Channel.BindCarRegisterWithBill(BillNo, crd, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> BindCarRegisterWithBillAsync(string BillNo, CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterDetail crd, int cmstId) {
            return base.Channel.BindCarRegisterWithBillAsync(BillNo, crd, cmstId);
        }
        
        public string QueryCarRegisterById(long creId, int cmstId) {
            return base.Channel.QueryCarRegisterById(creId, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryCarRegisterByIdAsync(long creId, int cmstId) {
            return base.Channel.QueryCarRegisterByIdAsync(creId, cmstId);
        }
        
        public string QueryCarRegisterByBillNo(string BillNo, int cmstId) {
            return base.Channel.QueryCarRegisterByBillNo(BillNo, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryCarRegisterByBillNoAsync(string BillNo, int cmstId) {
            return base.Channel.QueryCarRegisterByBillNoAsync(BillNo, cmstId);
        }
        
        public string QueryCarRegisterByCarNo(string carNo, int cmstId) {
            return base.Channel.QueryCarRegisterByCarNo(carNo, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryCarRegisterByCarNoAsync(string carNo, int cmstId) {
            return base.Channel.QueryCarRegisterByCarNoAsync(carNo, cmstId);
        }
        
        public string QueryCarRegisterPageInfo(CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterQuery crq, string queryFields, int page, int pageSize) {
            return base.Channel.QueryCarRegisterPageInfo(crq, queryFields, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<string> QueryCarRegisterPageInfoAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegisterQuery crq, string queryFields, int page, int pageSize) {
            return base.Channel.QueryCarRegisterPageInfoAsync(crq, queryFields, page, pageSize);
        }
        
        public string QueryOutPlanByCarRegisterNo(string CarRegisterNo, int cmstId) {
            return base.Channel.QueryOutPlanByCarRegisterNo(CarRegisterNo, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryOutPlanByCarRegisterNoAsync(string CarRegisterNo, int cmstId) {
            return base.Channel.QueryOutPlanByCarRegisterNoAsync(CarRegisterNo, cmstId);
        }
        
        public string QueryInStoreBillByCarRegisterNo(string CarRegisterNo, int cmstId) {
            return base.Channel.QueryInStoreBillByCarRegisterNo(CarRegisterNo, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryInStoreBillByCarRegisterNoAsync(string CarRegisterNo, int cmstId) {
            return base.Channel.QueryInStoreBillByCarRegisterNoAsync(CarRegisterNo, cmstId);
        }
        
        public string CheckCarRegister(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c) {
            return base.Channel.CheckCarRegister(c);
        }
        
        public System.Threading.Tasks.Task<string> CheckCarRegisterAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c) {
            return base.Channel.CheckCarRegisterAsync(c);
        }
        
        public string QueryAllCarRegister(int cmstId) {
            return base.Channel.QueryAllCarRegister(cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryAllCarRegisterAsync(int cmstId) {
            return base.Channel.QueryAllCarRegisterAsync(cmstId);
        }
        
        public string QueryAllCarRegisterId(int cmstId) {
            return base.Channel.QueryAllCarRegisterId(cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryAllCarRegisterIdAsync(int cmstId) {
            return base.Channel.QueryAllCarRegisterIdAsync(cmstId);
        }
        
        public string QueryCarRegisterByCarNum(string carNum, int carType, int cmstId) {
            return base.Channel.QueryCarRegisterByCarNum(carNum, carType, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryCarRegisterByCarNumAsync(string carNum, int carType, int cmstId) {
            return base.Channel.QueryCarRegisterByCarNumAsync(carNum, carType, cmstId);
        }
        
        public string QueryCarRegisterDetailCountByBillNo(long crdBillNo, int Type) {
            return base.Channel.QueryCarRegisterDetailCountByBillNo(crdBillNo, Type);
        }
        
        public System.Threading.Tasks.Task<string> QueryCarRegisterDetailCountByBillNoAsync(long crdBillNo, int Type) {
            return base.Channel.QueryCarRegisterDetailCountByBillNoAsync(crdBillNo, Type);
        }
        
        public string QueryCarRegistersByBillNoAndBillType(long billNo, int billType, int cmstId) {
            return base.Channel.QueryCarRegistersByBillNoAndBillType(billNo, billType, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> QueryCarRegistersByBillNoAndBillTypeAsync(long billNo, int billType, int cmstId) {
            return base.Channel.QueryCarRegistersByBillNoAndBillTypeAsync(billNo, billType, cmstId);
        }
        
        public string UnBindCarRegisterWithBill(long BillNo, long carRegisterId, int cmstId) {
            return base.Channel.UnBindCarRegisterWithBill(BillNo, carRegisterId, cmstId);
        }
        
        public System.Threading.Tasks.Task<string> UnBindCarRegisterWithBillAsync(long BillNo, long carRegisterId, int cmstId) {
            return base.Channel.UnBindCarRegisterWithBillAsync(BillNo, carRegisterId, cmstId);
        }
        
        public CMST.Storage.Client.Proxy.CarManageProxy.CarRegister GenerateCarRegisterClass() {
            return base.Channel.GenerateCarRegisterClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.CarManageProxy.CarRegister> GenerateCarRegisterClassAsync() {
            return base.Channel.GenerateCarRegisterClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.CarManageProxy.OutStoreCheck GenerateOutStoreCheckClass() {
            return base.Channel.GenerateOutStoreCheckClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.CarManageProxy.OutStoreCheck> GenerateOutStoreCheckClassAsync() {
            return base.Channel.GenerateOutStoreCheckClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.CarManageProxy.InStoreCheck GenerateInStoreCheckClass() {
            return base.Channel.GenerateInStoreCheckClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.CarManageProxy.InStoreCheck> GenerateInStoreCheckClassAsync() {
            return base.Channel.GenerateInStoreCheckClassAsync();
        }
        
        public string UpdateRemakeByCreID(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c) {
            return base.Channel.UpdateRemakeByCreID(c);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRemakeByCreIDAsync(CMST.Storage.Client.Proxy.CarManageProxy.CarRegister c) {
            return base.Channel.UpdateRemakeByCreIDAsync(c);
        }
    }
}
