//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockModelData
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockModel", Namespace="http://schemas.datacontract.org/2004/07/StockModelData")]
    public partial class StockModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CmstIDField;
        
        private System.Nullable<int> CompanyIDField;
        
        private string CompanyNameField;
        
        private System.Nullable<int> DepotIDField;
        
        private System.DateTime MakeTimeField;
        
        private int MakerField;
        
        private string MakerNameField;
        
        private System.Nullable<int> ReservoirIDField;
        
        private string ReservoirNameField;
        
        private int StatusField;
        
        private long StocktakingIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmstID
        {
            get
            {
                return this.CmstIDField;
            }
            set
            {
                this.CmstIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyID
        {
            get
            {
                return this.CompanyIDField;
            }
            set
            {
                this.CompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DepotID
        {
            get
            {
                return this.DepotIDField;
            }
            set
            {
                this.DepotIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MakeTime
        {
            get
            {
                return this.MakeTimeField;
            }
            set
            {
                this.MakeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Maker
        {
            get
            {
                return this.MakerField;
            }
            set
            {
                this.MakerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakerName
        {
            get
            {
                return this.MakerNameField;
            }
            set
            {
                this.MakerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReservoirID
        {
            get
            {
                return this.ReservoirIDField;
            }
            set
            {
                this.ReservoirIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservoirName
        {
            get
            {
                return this.ReservoirNameField;
            }
            set
            {
                this.ReservoirNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StocktakingID
        {
            get
            {
                return this.StocktakingIDField;
            }
            set
            {
                this.StocktakingIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StocktakingQuery", Namespace="http://schemas.datacontract.org/2004/07/StockModelData")]
    public partial class StocktakingQuery : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CmstIDField;
        
        private int CompanyIDField;
        
        private long CurrentMinIDField;
        
        private int DepotIDField;
        
        private System.DateTime EndTimeField;
        
        private int GalIDField;
        
        private int RequesterField;
        
        private int ReservoirIDField;
        
        private System.DateTime StartTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmstID
        {
            get
            {
                return this.CmstIDField;
            }
            set
            {
                this.CmstIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID
        {
            get
            {
                return this.CompanyIDField;
            }
            set
            {
                this.CompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CurrentMinID
        {
            get
            {
                return this.CurrentMinIDField;
            }
            set
            {
                this.CurrentMinIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepotID
        {
            get
            {
                return this.DepotIDField;
            }
            set
            {
                this.DepotIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GalID
        {
            get
            {
                return this.GalIDField;
            }
            set
            {
                this.GalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Requester
        {
            get
            {
                return this.RequesterField;
            }
            set
            {
                this.RequesterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservoirID
        {
            get
            {
                return this.ReservoirIDField;
            }
            set
            {
                this.ReservoirIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockTakingManageProxy")]
public interface StockTakingManageProxy
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/AddStocktakingBill", ReplyAction="http://tempuri.org/IStocktakingManage/AddStocktakingBillResponse")]
    string AddStocktakingBill(StockModelData.StockModel sm);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/AddStocktakingBill", ReplyAction="http://tempuri.org/IStocktakingManage/AddStocktakingBillResponse")]
    System.Threading.Tasks.Task<string> AddStocktakingBillAsync(StockModelData.StockModel sm);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/QueryStocktakingBillInfos", ReplyAction="http://tempuri.org/IStocktakingManage/QueryStocktakingBillInfosResponse")]
    string QueryStocktakingBillInfos(StockModelData.StocktakingQuery sq);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/QueryStocktakingBillInfos", ReplyAction="http://tempuri.org/IStocktakingManage/QueryStocktakingBillInfosResponse")]
    System.Threading.Tasks.Task<string> QueryStocktakingBillInfosAsync(StockModelData.StocktakingQuery sq);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetailsInfo", ReplyAction="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetailsInfoResponse")]
    string QueryStocktakingBillDetailsInfo(long stocktakingId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetailsInfo", ReplyAction="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetailsInfoResponse")]
    System.Threading.Tasks.Task<string> QueryStocktakingBillDetailsInfoAsync(long stocktakingId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetial", ReplyAction="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetialResponse")]
    string QueryStocktakingBillDetial(long stocktakingDetailId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetial", ReplyAction="http://tempuri.org/IStocktakingManage/QueryStocktakingBillDetialResponse")]
    System.Threading.Tasks.Task<string> QueryStocktakingBillDetialAsync(long stocktakingDetailId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/CheckStocktakingDetail", ReplyAction="http://tempuri.org/IStocktakingManage/CheckStocktakingDetailResponse")]
    string CheckStocktakingDetail(long stocktakingId, long stocktakingDetailId, int result, int checker, string remark);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStocktakingManage/CheckStocktakingDetail", ReplyAction="http://tempuri.org/IStocktakingManage/CheckStocktakingDetailResponse")]
    System.Threading.Tasks.Task<string> CheckStocktakingDetailAsync(long stocktakingId, long stocktakingDetailId, int result, int checker, string remark);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface StockTakingManageProxyChannel : StockTakingManageProxy, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StockTakingManageProxyClient : System.ServiceModel.ClientBase<StockTakingManageProxy>, StockTakingManageProxy
{
    
    public StockTakingManageProxyClient()
    {
    }
    
    public StockTakingManageProxyClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StockTakingManageProxyClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StockTakingManageProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StockTakingManageProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string AddStocktakingBill(StockModelData.StockModel sm)
    {
        return base.Channel.AddStocktakingBill(sm);
    }
    
    public System.Threading.Tasks.Task<string> AddStocktakingBillAsync(StockModelData.StockModel sm)
    {
        return base.Channel.AddStocktakingBillAsync(sm);
    }
    
    public string QueryStocktakingBillInfos(StockModelData.StocktakingQuery sq)
    {
        return base.Channel.QueryStocktakingBillInfos(sq);
    }
    
    public System.Threading.Tasks.Task<string> QueryStocktakingBillInfosAsync(StockModelData.StocktakingQuery sq)
    {
        return base.Channel.QueryStocktakingBillInfosAsync(sq);
    }
    
    public string QueryStocktakingBillDetailsInfo(long stocktakingId)
    {
        return base.Channel.QueryStocktakingBillDetailsInfo(stocktakingId);
    }
    
    public System.Threading.Tasks.Task<string> QueryStocktakingBillDetailsInfoAsync(long stocktakingId)
    {
        return base.Channel.QueryStocktakingBillDetailsInfoAsync(stocktakingId);
    }
    
    public string QueryStocktakingBillDetial(long stocktakingDetailId)
    {
        return base.Channel.QueryStocktakingBillDetial(stocktakingDetailId);
    }
    
    public System.Threading.Tasks.Task<string> QueryStocktakingBillDetialAsync(long stocktakingDetailId)
    {
        return base.Channel.QueryStocktakingBillDetialAsync(stocktakingDetailId);
    }
    
    public string CheckStocktakingDetail(long stocktakingId, long stocktakingDetailId, int result, int checker, string remark)
    {
        return base.Channel.CheckStocktakingDetail(stocktakingId, stocktakingDetailId, result, checker, remark);
    }
    
    public System.Threading.Tasks.Task<string> CheckStocktakingDetailAsync(long stocktakingId, long stocktakingDetailId, int result, int checker, string remark)
    {
        return base.Channel.CheckStocktakingDetailAsync(stocktakingId, stocktakingDetailId, result, checker, remark);
    }
}
