//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMST.Storage.Client.Proxy.MachingManageProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Maching", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.MachingManage")]
    [System.SerializableAttribute()]
    public partial class Maching : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CheckTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CheckerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CmstIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IfDelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MacIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MakeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CMST.Storage.Client.Proxy.MachingManageProxy.MachingDetail> MdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CheckTime {
            get {
                return this.CheckTimeField;
            }
            set {
                if ((this.CheckTimeField.Equals(value) != true)) {
                    this.CheckTimeField = value;
                    this.RaisePropertyChanged("CheckTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Checker {
            get {
                return this.CheckerField;
            }
            set {
                if ((this.CheckerField.Equals(value) != true)) {
                    this.CheckerField = value;
                    this.RaisePropertyChanged("Checker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckerName {
            get {
                return this.CheckerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckerNameField, value) != true)) {
                    this.CheckerNameField = value;
                    this.RaisePropertyChanged("CheckerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmstID {
            get {
                return this.CmstIDField;
            }
            set {
                if ((this.CmstIDField.Equals(value) != true)) {
                    this.CmstIDField = value;
                    this.RaisePropertyChanged("CmstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepID {
            get {
                return this.DepIDField;
            }
            set {
                if ((this.DepIDField.Equals(value) != true)) {
                    this.DepIDField = value;
                    this.RaisePropertyChanged("DepID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepName {
            get {
                return this.DepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepNameField, value) != true)) {
                    this.DepNameField = value;
                    this.RaisePropertyChanged("DepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IfDel {
            get {
                return this.IfDelField;
            }
            set {
                if ((this.IfDelField.Equals(value) != true)) {
                    this.IfDelField = value;
                    this.RaisePropertyChanged("IfDel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MacID {
            get {
                return this.MacIDField;
            }
            set {
                if ((this.MacIDField.Equals(value) != true)) {
                    this.MacIDField = value;
                    this.RaisePropertyChanged("MacID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MakeTime {
            get {
                return this.MakeTimeField;
            }
            set {
                if ((this.MakeTimeField.Equals(value) != true)) {
                    this.MakeTimeField = value;
                    this.RaisePropertyChanged("MakeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Maker {
            get {
                return this.MakerField;
            }
            set {
                if ((this.MakerField.Equals(value) != true)) {
                    this.MakerField = value;
                    this.RaisePropertyChanged("Maker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakerName {
            get {
                return this.MakerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakerNameField, value) != true)) {
                    this.MakerNameField = value;
                    this.RaisePropertyChanged("MakerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CMST.Storage.Client.Proxy.MachingManageProxy.MachingDetail> Mds {
            get {
                return this.MdsField;
            }
            set {
                if ((object.ReferenceEquals(this.MdsField, value) != true)) {
                    this.MdsField = value;
                    this.RaisePropertyChanged("Mds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachingDetail", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.MachingManage")]
    [System.SerializableAttribute()]
    public partial class MachingDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GalDescriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MdeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MdeMacIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewGoodsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewGradeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewManNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewSkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewSkuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewSpecNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldGoodsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldGradeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldManNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OldSkuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldSkuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldSpecNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RecordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GalDescript {
            get {
                return this.GalDescriptField;
            }
            set {
                if ((object.ReferenceEquals(this.GalDescriptField, value) != true)) {
                    this.GalDescriptField = value;
                    this.RaisePropertyChanged("GalDescript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GalID {
            get {
                return this.GalIDField;
            }
            set {
                if ((this.GalIDField.Equals(value) != true)) {
                    this.GalIDField = value;
                    this.RaisePropertyChanged("GalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GalName {
            get {
                return this.GalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GalNameField, value) != true)) {
                    this.GalNameField = value;
                    this.RaisePropertyChanged("GalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MdeID {
            get {
                return this.MdeIDField;
            }
            set {
                if ((this.MdeIDField.Equals(value) != true)) {
                    this.MdeIDField = value;
                    this.RaisePropertyChanged("MdeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MdeMacID {
            get {
                return this.MdeMacIDField;
            }
            set {
                if ((this.MdeMacIDField.Equals(value) != true)) {
                    this.MdeMacIDField = value;
                    this.RaisePropertyChanged("MdeMacID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NAN {
            get {
                return this.NANField;
            }
            set {
                if ((this.NANField.Equals(value) != true)) {
                    this.NANField = value;
                    this.RaisePropertyChanged("NAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NPN {
            get {
                return this.NPNField;
            }
            set {
                if ((this.NPNField.Equals(value) != true)) {
                    this.NPNField = value;
                    this.RaisePropertyChanged("NPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewGoodsName {
            get {
                return this.NewGoodsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewGoodsNameField, value) != true)) {
                    this.NewGoodsNameField = value;
                    this.RaisePropertyChanged("NewGoodsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewGradeName {
            get {
                return this.NewGradeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewGradeNameField, value) != true)) {
                    this.NewGradeNameField = value;
                    this.RaisePropertyChanged("NewGradeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewManName {
            get {
                return this.NewManNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewManNameField, value) != true)) {
                    this.NewManNameField = value;
                    this.RaisePropertyChanged("NewManName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPackage {
            get {
                return this.NewPackageField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPackageField, value) != true)) {
                    this.NewPackageField = value;
                    this.RaisePropertyChanged("NewPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewProductName {
            get {
                return this.NewProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewProductNameField, value) != true)) {
                    this.NewProductNameField = value;
                    this.RaisePropertyChanged("NewProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewSku {
            get {
                return this.NewSkuField;
            }
            set {
                if ((this.NewSkuField.Equals(value) != true)) {
                    this.NewSkuField = value;
                    this.RaisePropertyChanged("NewSku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewSkuName {
            get {
                return this.NewSkuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewSkuNameField, value) != true)) {
                    this.NewSkuNameField = value;
                    this.RaisePropertyChanged("NewSkuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewSpecName {
            get {
                return this.NewSpecNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewSpecNameField, value) != true)) {
                    this.NewSpecNameField = value;
                    this.RaisePropertyChanged("NewSpecName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OAN {
            get {
                return this.OANField;
            }
            set {
                if ((this.OANField.Equals(value) != true)) {
                    this.OANField = value;
                    this.RaisePropertyChanged("OAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OPN {
            get {
                return this.OPNField;
            }
            set {
                if ((this.OPNField.Equals(value) != true)) {
                    this.OPNField = value;
                    this.RaisePropertyChanged("OPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldGoodsName {
            get {
                return this.OldGoodsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldGoodsNameField, value) != true)) {
                    this.OldGoodsNameField = value;
                    this.RaisePropertyChanged("OldGoodsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldGradeName {
            get {
                return this.OldGradeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldGradeNameField, value) != true)) {
                    this.OldGradeNameField = value;
                    this.RaisePropertyChanged("OldGradeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldManName {
            get {
                return this.OldManNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldManNameField, value) != true)) {
                    this.OldManNameField = value;
                    this.RaisePropertyChanged("OldManName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldPackage {
            get {
                return this.OldPackageField;
            }
            set {
                if ((object.ReferenceEquals(this.OldPackageField, value) != true)) {
                    this.OldPackageField = value;
                    this.RaisePropertyChanged("OldPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldProductName {
            get {
                return this.OldProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldProductNameField, value) != true)) {
                    this.OldProductNameField = value;
                    this.RaisePropertyChanged("OldProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OldSku {
            get {
                return this.OldSkuField;
            }
            set {
                if ((this.OldSkuField.Equals(value) != true)) {
                    this.OldSkuField = value;
                    this.RaisePropertyChanged("OldSku");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldSkuName {
            get {
                return this.OldSkuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldSkuNameField, value) != true)) {
                    this.OldSkuNameField = value;
                    this.RaisePropertyChanged("OldSkuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldSpecName {
            get {
                return this.OldSpecNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OldSpecNameField, value) != true)) {
                    this.OldSpecNameField = value;
                    this.RaisePropertyChanged("OldSpecName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MechingQuery", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.MachingManage")]
    [System.SerializableAttribute()]
    public partial class MechingQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CmstIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> MacIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmstID {
            get {
                return this.CmstIDField;
            }
            set {
                if ((this.CmstIDField.Equals(value) != true)) {
                    this.CmstIDField = value;
                    this.RaisePropertyChanged("CmstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MacID {
            get {
                return this.MacIDField;
            }
            set {
                if ((this.MacIDField.Equals(value) != true)) {
                    this.MacIDField = value;
                    this.RaisePropertyChanged("MacID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((this.RequesterField.Equals(value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeType {
            get {
                return this.TimeTypeField;
            }
            set {
                if ((this.TimeTypeField.Equals(value) != true)) {
                    this.TimeTypeField = value;
                    this.RaisePropertyChanged("TimeType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MachingManageProxy.IMachingManageProxy")]
    public interface IMachingManageProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/SaveMechingTemporary", ReplyAction="http://tempuri.org/IMachingManage/SaveMechingTemporaryResponse")]
        string SaveMechingTemporary(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/SaveMechingTemporary", ReplyAction="http://tempuri.org/IMachingManage/SaveMechingTemporaryResponse")]
        System.Threading.Tasks.Task<string> SaveMechingTemporaryAsync(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/SaveCheck", ReplyAction="http://tempuri.org/IMachingManage/SaveCheckResponse")]
        string SaveCheck(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/SaveCheck", ReplyAction="http://tempuri.org/IMachingManage/SaveCheckResponse")]
        System.Threading.Tasks.Task<string> SaveCheckAsync(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/QueryMachingBill", ReplyAction="http://tempuri.org/IMachingManage/QueryMachingBillResponse")]
        string QueryMachingBill(long macId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/QueryMachingBill", ReplyAction="http://tempuri.org/IMachingManage/QueryMachingBillResponse")]
        System.Threading.Tasks.Task<string> QueryMachingBillAsync(long macId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/QueryMachingBillPageInfo", ReplyAction="http://tempuri.org/IMachingManage/QueryMachingBillPageInfoResponse")]
        string QueryMachingBillPageInfo(CMST.Storage.Client.Proxy.MachingManageProxy.MechingQuery mq, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/QueryMachingBillPageInfo", ReplyAction="http://tempuri.org/IMachingManage/QueryMachingBillPageInfoResponse")]
        System.Threading.Tasks.Task<string> QueryMachingBillPageInfoAsync(CMST.Storage.Client.Proxy.MachingManageProxy.MechingQuery mq, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/SaveInvalidMaching", ReplyAction="http://tempuri.org/IMachingManage/SaveInvalidMachingResponse")]
        string SaveInvalidMaching(long id, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachingManage/SaveInvalidMaching", ReplyAction="http://tempuri.org/IMachingManage/SaveInvalidMachingResponse")]
        System.Threading.Tasks.Task<string> SaveInvalidMachingAsync(long id, int operatorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMachingManageProxyChannel : CMST.Storage.Client.Proxy.MachingManageProxy.IMachingManageProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MachingManageProxyClient : System.ServiceModel.ClientBase<CMST.Storage.Client.Proxy.MachingManageProxy.IMachingManageProxy>, CMST.Storage.Client.Proxy.MachingManageProxy.IMachingManageProxy {
        
        public MachingManageProxyClient() {
        }
        
        public MachingManageProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MachingManageProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachingManageProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachingManageProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveMechingTemporary(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m) {
            return base.Channel.SaveMechingTemporary(m);
        }
        
        public System.Threading.Tasks.Task<string> SaveMechingTemporaryAsync(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m) {
            return base.Channel.SaveMechingTemporaryAsync(m);
        }
        
        public string SaveCheck(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m) {
            return base.Channel.SaveCheck(m);
        }
        
        public System.Threading.Tasks.Task<string> SaveCheckAsync(CMST.Storage.Client.Proxy.MachingManageProxy.Maching m) {
            return base.Channel.SaveCheckAsync(m);
        }
        
        public string QueryMachingBill(long macId) {
            return base.Channel.QueryMachingBill(macId);
        }
        
        public System.Threading.Tasks.Task<string> QueryMachingBillAsync(long macId) {
            return base.Channel.QueryMachingBillAsync(macId);
        }
        
        public string QueryMachingBillPageInfo(CMST.Storage.Client.Proxy.MachingManageProxy.MechingQuery mq, string queryFields, int page, int pageSize) {
            return base.Channel.QueryMachingBillPageInfo(mq, queryFields, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<string> QueryMachingBillPageInfoAsync(CMST.Storage.Client.Proxy.MachingManageProxy.MechingQuery mq, string queryFields, int page, int pageSize) {
            return base.Channel.QueryMachingBillPageInfoAsync(mq, queryFields, page, pageSize);
        }
        
        public string SaveInvalidMaching(long id, int operatorId) {
            return base.Channel.SaveInvalidMaching(id, operatorId);
        }
        
        public System.Threading.Tasks.Task<string> SaveInvalidMachingAsync(long id, int operatorId) {
            return base.Channel.SaveInvalidMachingAsync(id, operatorId);
        }
    }
}
