//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMST.Storage.Client.Proxy.DataModelProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageInfo", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Common")]
    [System.SerializableAttribute()]
    public partial class PageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet FirstPageResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet FirstPageResult {
            get {
                return this.FirstPageResultField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstPageResultField, value) != true)) {
                    this.FirstPageResultField = value;
                    this.RaisePropertyChanged("FirstPageResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageCount {
            get {
                return this.PageCountField;
            }
            set {
                if ((this.PageCountField.Equals(value) != true)) {
                    this.PageCountField = value;
                    this.RaisePropertyChanged("PageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Records {
            get {
                return this.RecordsField;
            }
            set {
                if ((this.RecordsField.Equals(value) != true)) {
                    this.RecordsField = value;
                    this.RaisePropertyChanged("Records");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuEntity", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.BaseManage")]
    [System.SerializableAttribute()]
    public partial class MenuEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuFatherIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity> OperationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity> SubMenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SystemIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuFatherID {
            get {
                return this.MenuFatherIDField;
            }
            set {
                if ((this.MenuFatherIDField.Equals(value) != true)) {
                    this.MenuFatherIDField = value;
                    this.RaisePropertyChanged("MenuFatherID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuID {
            get {
                return this.MenuIDField;
            }
            set {
                if ((this.MenuIDField.Equals(value) != true)) {
                    this.MenuIDField = value;
                    this.RaisePropertyChanged("MenuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuName {
            get {
                return this.MenuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuNameField, value) != true)) {
                    this.MenuNameField = value;
                    this.RaisePropertyChanged("MenuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuRank {
            get {
                return this.MenuRankField;
            }
            set {
                if ((this.MenuRankField.Equals(value) != true)) {
                    this.MenuRankField = value;
                    this.RaisePropertyChanged("MenuRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity> Operations {
            get {
                return this.OperationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationsField, value) != true)) {
                    this.OperationsField = value;
                    this.RaisePropertyChanged("Operations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity> SubMenus {
            get {
                return this.SubMenusField;
            }
            set {
                if ((object.ReferenceEquals(this.SubMenusField, value) != true)) {
                    this.SubMenusField = value;
                    this.RaisePropertyChanged("SubMenus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemID {
            get {
                return this.SystemIDField;
            }
            set {
                if ((this.SystemIDField.Equals(value) != true)) {
                    this.SystemIDField = value;
                    this.RaisePropertyChanged("SystemID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationEntity", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.BaseManage")]
    [System.SerializableAttribute()]
    public partial class OperationEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuID {
            get {
                return this.MenuIDField;
            }
            set {
                if ((this.MenuIDField.Equals(value) != true)) {
                    this.MenuIDField = value;
                    this.RaisePropertyChanged("MenuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationID {
            get {
                return this.OperationIDField;
            }
            set {
                if ((this.OperationIDField.Equals(value) != true)) {
                    this.OperationIDField = value;
                    this.RaisePropertyChanged("OperationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName {
            get {
                return this.OperationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationNameField, value) != true)) {
                    this.OperationNameField = value;
                    this.RaisePropertyChanged("OperationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuUI", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.BaseManage")]
    [System.SerializableAttribute()]
    public partial class MenuUI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity> MesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity> OesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity> Mes {
            get {
                return this.MesField;
            }
            set {
                if ((object.ReferenceEquals(this.MesField, value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity> Oes {
            get {
                return this.OesField;
            }
            set {
                if ((object.ReferenceEquals(this.OesField, value) != true)) {
                    this.OesField = value;
                    this.RaisePropertyChanged("Oes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedbackInfomation", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CMST.Storage.Client.Proxy.DataModelProxy.PageInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CMST.Storage.Client.Proxy.DataModelProxy.STATUS_ADAPTER))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CMST.Storage.Client.Proxy.DataModelProxy.Sku))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CMST.Storage.Client.Proxy.DataModelProxy.BillType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CMST.Storage.Client.Proxy.DataModelProxy.MenuUI))]
    public partial class FeedbackInfomation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CMST.Storage.Client.Proxy.DataModelProxy.STATUS_ADAPTER ErrorStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedbackMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CMST.Storage.Client.Proxy.DataModelProxy.STATUS_ADAPTER ErrorStatus {
            get {
                return this.ErrorStatusField;
            }
            set {
                if ((this.ErrorStatusField.Equals(value) != true)) {
                    this.ErrorStatusField = value;
                    this.RaisePropertyChanged("ErrorStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedbackMessage {
            get {
                return this.FeedbackMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackMessageField, value) != true)) {
                    this.FeedbackMessageField = value;
                    this.RaisePropertyChanged("FeedbackMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STATUS_ADAPTER", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Common")]
    public enum STATUS_ADAPTER : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DB_CONNECT_NORMAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DB_CONNECT_FAILD = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DB_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IP_NORMAL = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IP_EMPTY = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IP_FORMAT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QUERY_NORMAL = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QUERY_ERROR = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INSERT_NORMAL = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INSERT_ERROR = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAVE_SUCCESS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAVE_FAILED = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEl_SUCCESS = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEL_FAILED = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QUERY_NODATA = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHECK_SUCCESS = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHECK_FAILED = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCEL_CHECK_SUCCESS = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCEL_CHECK_FAILED = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOGIN_SUCCESS = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOGIN_FAILED = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHECK_PWD_SUCCESS = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHECK_PWD_FAILED = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIND_SUCCESS = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIND_FAILED = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TEMPORARY_SUCCESS = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TEMPORARY_FAILED = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REVIEW_SUCCESS = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REVIEW_FAILED = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONFIRM_SUCCESS = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONFIRM_FAILED = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QUERY_REPEAT = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedisCluster_CONNECT_NORMAL = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RedisCluster_CONNECT_FAILD = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATE_SUCCESS = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPDATE_ERROR = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOGOUT_SUCCESS = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOGOUT_FAILED = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REVERSE_SUCCESS = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REVERSE_FAILED = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACCOUNT_PASSWORD_ERROR = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESERIALIZEPARA_FAILED = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPORT_SUCCESS = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMPORT_FAILED = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUBMIT_SUCCESS = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUBMIT_FAILED = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELSUBMIT_SUCCESS = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELSUBMIT_FAILED = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RETURN_SUCCESS = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RETURN_FAILED = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_SUCCESS = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_FAILED = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        END_SUCCESS = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        END_FAILED = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESTART_SUCCESS = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESTART_FAILED = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WITHDRAW_SUCCESS = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WITHDRAW_FAILED = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHARGE_NORMAL = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHARGE_EMPTY = 59,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sku", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.Account")]
    [System.SerializableAttribute()]
    public partial class Sku : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AuxIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SignTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkuIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpareField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AuxID {
            get {
                return this.AuxIDField;
            }
            set {
                if ((this.AuxIDField.Equals(value) != true)) {
                    this.AuxIDField = value;
                    this.RaisePropertyChanged("AuxID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignNum {
            get {
                return this.SignNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SignNumField, value) != true)) {
                    this.SignNumField = value;
                    this.RaisePropertyChanged("SignNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SignTypeID {
            get {
                return this.SignTypeIDField;
            }
            set {
                if ((this.SignTypeIDField.Equals(value) != true)) {
                    this.SignTypeIDField = value;
                    this.RaisePropertyChanged("SignTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkuID {
            get {
                return this.SkuIDField;
            }
            set {
                if ((this.SkuIDField.Equals(value) != true)) {
                    this.SkuIDField = value;
                    this.RaisePropertyChanged("SkuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkuName {
            get {
                return this.SkuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuNameField, value) != true)) {
                    this.SkuNameField = value;
                    this.RaisePropertyChanged("SkuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spare {
            get {
                return this.SpareField;
            }
            set {
                if ((object.ReferenceEquals(this.SpareField, value) != true)) {
                    this.SpareField = value;
                    this.RaisePropertyChanged("Spare");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillType", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.Account")]
    [System.SerializableAttribute()]
    public partial class BillType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillTypeID {
            get {
                return this.BillTypeIDField;
            }
            set {
                if ((this.BillTypeIDField.Equals(value) != true)) {
                    this.BillTypeIDField = value;
                    this.RaisePropertyChanged("BillTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillTypeName {
            get {
                return this.BillTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BillTypeNameField, value) != true)) {
                    this.BillTypeNameField = value;
                    this.RaisePropertyChanged("BillTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataModelProxy.IDataModelProxy")]
    public interface IDataModelProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/GeneratePageInfoClass", ReplyAction="http://tempuri.org/IDataModel/GeneratePageInfoClassResponse")]
        CMST.Storage.Client.Proxy.DataModelProxy.PageInfo GeneratePageInfoClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/GeneratePageInfoClass", ReplyAction="http://tempuri.org/IDataModel/GeneratePageInfoClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.PageInfo> GeneratePageInfoClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/MenuEntityClass", ReplyAction="http://tempuri.org/IDataModel/MenuEntityClassResponse")]
        CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity MenuEntityClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/MenuEntityClass", ReplyAction="http://tempuri.org/IDataModel/MenuEntityClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity> MenuEntityClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/MenuUIClass", ReplyAction="http://tempuri.org/IDataModel/MenuUIClassResponse")]
        CMST.Storage.Client.Proxy.DataModelProxy.MenuUI MenuUIClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/MenuUIClass", ReplyAction="http://tempuri.org/IDataModel/MenuUIClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.MenuUI> MenuUIClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/OperationEntityClass", ReplyAction="http://tempuri.org/IDataModel/OperationEntityClassResponse")]
        CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity OperationEntityClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/OperationEntityClass", ReplyAction="http://tempuri.org/IDataModel/OperationEntityClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity> OperationEntityClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/FeedbackInfomationClass", ReplyAction="http://tempuri.org/IDataModel/FeedbackInfomationClassResponse")]
        CMST.Storage.Client.Proxy.DataModelProxy.FeedbackInfomation FeedbackInfomationClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/FeedbackInfomationClass", ReplyAction="http://tempuri.org/IDataModel/FeedbackInfomationClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.FeedbackInfomation> FeedbackInfomationClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/SkuClass", ReplyAction="http://tempuri.org/IDataModel/SkuClassResponse")]
        CMST.Storage.Client.Proxy.DataModelProxy.Sku SkuClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/SkuClass", ReplyAction="http://tempuri.org/IDataModel/SkuClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.Sku> SkuClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/BillTypeClass", ReplyAction="http://tempuri.org/IDataModel/BillTypeClassResponse")]
        CMST.Storage.Client.Proxy.DataModelProxy.BillType BillTypeClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataModel/BillTypeClass", ReplyAction="http://tempuri.org/IDataModel/BillTypeClassResponse")]
        System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.BillType> BillTypeClassAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataModelProxyChannel : CMST.Storage.Client.Proxy.DataModelProxy.IDataModelProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataModelProxyClient : System.ServiceModel.ClientBase<CMST.Storage.Client.Proxy.DataModelProxy.IDataModelProxy>, CMST.Storage.Client.Proxy.DataModelProxy.IDataModelProxy {
        
        public DataModelProxyClient() {
        }
        
        public DataModelProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataModelProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataModelProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataModelProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CMST.Storage.Client.Proxy.DataModelProxy.PageInfo GeneratePageInfoClass() {
            return base.Channel.GeneratePageInfoClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.PageInfo> GeneratePageInfoClassAsync() {
            return base.Channel.GeneratePageInfoClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity MenuEntityClass() {
            return base.Channel.MenuEntityClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.MenuEntity> MenuEntityClassAsync() {
            return base.Channel.MenuEntityClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.DataModelProxy.MenuUI MenuUIClass() {
            return base.Channel.MenuUIClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.MenuUI> MenuUIClassAsync() {
            return base.Channel.MenuUIClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity OperationEntityClass() {
            return base.Channel.OperationEntityClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.OperationEntity> OperationEntityClassAsync() {
            return base.Channel.OperationEntityClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.DataModelProxy.FeedbackInfomation FeedbackInfomationClass() {
            return base.Channel.FeedbackInfomationClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.FeedbackInfomation> FeedbackInfomationClassAsync() {
            return base.Channel.FeedbackInfomationClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.DataModelProxy.Sku SkuClass() {
            return base.Channel.SkuClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.Sku> SkuClassAsync() {
            return base.Channel.SkuClassAsync();
        }
        
        public CMST.Storage.Client.Proxy.DataModelProxy.BillType BillTypeClass() {
            return base.Channel.BillTypeClass();
        }
        
        public System.Threading.Tasks.Task<CMST.Storage.Client.Proxy.DataModelProxy.BillType> BillTypeClassAsync() {
            return base.Channel.BillTypeClassAsync();
        }
    }
}
