//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMST.Storage.Client.Proxy.AdjustManageProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adjust", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.SpecialBusiness")]
    [System.SerializableAttribute()]
    public partial class Adjust : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AdjustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AdjustTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CMST.Storage.Client.Proxy.AdjustManageProxy.AdjustDetail> AdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CheckTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CheckerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CmstIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IfDelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IfOperateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MakeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AdjustID {
            get {
                return this.AdjustIDField;
            }
            set {
                if ((this.AdjustIDField.Equals(value) != true)) {
                    this.AdjustIDField = value;
                    this.RaisePropertyChanged("AdjustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AdjustTime {
            get {
                return this.AdjustTimeField;
            }
            set {
                if ((this.AdjustTimeField.Equals(value) != true)) {
                    this.AdjustTimeField = value;
                    this.RaisePropertyChanged("AdjustTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CMST.Storage.Client.Proxy.AdjustManageProxy.AdjustDetail> Ads {
            get {
                return this.AdsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdsField, value) != true)) {
                    this.AdsField = value;
                    this.RaisePropertyChanged("Ads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CheckTime {
            get {
                return this.CheckTimeField;
            }
            set {
                if ((this.CheckTimeField.Equals(value) != true)) {
                    this.CheckTimeField = value;
                    this.RaisePropertyChanged("CheckTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Checker {
            get {
                return this.CheckerField;
            }
            set {
                if ((this.CheckerField.Equals(value) != true)) {
                    this.CheckerField = value;
                    this.RaisePropertyChanged("Checker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckerName {
            get {
                return this.CheckerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckerNameField, value) != true)) {
                    this.CheckerNameField = value;
                    this.RaisePropertyChanged("CheckerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmstID {
            get {
                return this.CmstIDField;
            }
            set {
                if ((this.CmstIDField.Equals(value) != true)) {
                    this.CmstIDField = value;
                    this.RaisePropertyChanged("CmstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepID {
            get {
                return this.DepIDField;
            }
            set {
                if ((this.DepIDField.Equals(value) != true)) {
                    this.DepIDField = value;
                    this.RaisePropertyChanged("DepID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepName {
            get {
                return this.DepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepNameField, value) != true)) {
                    this.DepNameField = value;
                    this.RaisePropertyChanged("DepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IfDel {
            get {
                return this.IfDelField;
            }
            set {
                if ((this.IfDelField.Equals(value) != true)) {
                    this.IfDelField = value;
                    this.RaisePropertyChanged("IfDel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IfOperate {
            get {
                return this.IfOperateField;
            }
            set {
                if ((this.IfOperateField.Equals(value) != true)) {
                    this.IfOperateField = value;
                    this.RaisePropertyChanged("IfOperate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MakeTime {
            get {
                return this.MakeTimeField;
            }
            set {
                if ((this.MakeTimeField.Equals(value) != true)) {
                    this.MakeTimeField = value;
                    this.RaisePropertyChanged("MakeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Maker {
            get {
                return this.MakerField;
            }
            set {
                if ((this.MakerField.Equals(value) != true)) {
                    this.MakerField = value;
                    this.RaisePropertyChanged("Maker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakerName {
            get {
                return this.MakerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakerNameField, value) != true)) {
                    this.MakerNameField = value;
                    this.RaisePropertyChanged("MakerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdjustDetail", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.SpecialBusiness")]
    [System.SerializableAttribute()]
    public partial class AdjustDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AdjustDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AdjustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GalDescriptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkuIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AN {
            get {
                return this.ANField;
            }
            set {
                if ((this.ANField.Equals(value) != true)) {
                    this.ANField = value;
                    this.RaisePropertyChanged("AN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AdjustDetailID {
            get {
                return this.AdjustDetailIDField;
            }
            set {
                if ((this.AdjustDetailIDField.Equals(value) != true)) {
                    this.AdjustDetailIDField = value;
                    this.RaisePropertyChanged("AdjustDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AdjustID {
            get {
                return this.AdjustIDField;
            }
            set {
                if ((this.AdjustIDField.Equals(value) != true)) {
                    this.AdjustIDField = value;
                    this.RaisePropertyChanged("AdjustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descript {
            get {
                return this.DescriptField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptField, value) != true)) {
                    this.DescriptField = value;
                    this.RaisePropertyChanged("Descript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GalDescript {
            get {
                return this.GalDescriptField;
            }
            set {
                if ((object.ReferenceEquals(this.GalDescriptField, value) != true)) {
                    this.GalDescriptField = value;
                    this.RaisePropertyChanged("GalDescript");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GalID {
            get {
                return this.GalIDField;
            }
            set {
                if ((this.GalIDField.Equals(value) != true)) {
                    this.GalIDField = value;
                    this.RaisePropertyChanged("GalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GalName {
            get {
                return this.GalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GalNameField, value) != true)) {
                    this.GalNameField = value;
                    this.RaisePropertyChanged("GalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsName {
            get {
                return this.GoodsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsNameField, value) != true)) {
                    this.GoodsNameField = value;
                    this.RaisePropertyChanged("GoodsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeName {
            get {
                return this.GradeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeNameField, value) != true)) {
                    this.GradeNameField = value;
                    this.RaisePropertyChanged("GradeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManName {
            get {
                return this.ManNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManNameField, value) != true)) {
                    this.ManNameField = value;
                    this.RaisePropertyChanged("ManName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PN {
            get {
                return this.PNField;
            }
            set {
                if ((this.PNField.Equals(value) != true)) {
                    this.PNField = value;
                    this.RaisePropertyChanged("PN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageName {
            get {
                return this.PackageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageNameField, value) != true)) {
                    this.PackageNameField = value;
                    this.RaisePropertyChanged("PackageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignName {
            get {
                return this.SignNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SignNameField, value) != true)) {
                    this.SignNameField = value;
                    this.RaisePropertyChanged("SignName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignNum {
            get {
                return this.SignNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SignNumField, value) != true)) {
                    this.SignNumField = value;
                    this.RaisePropertyChanged("SignNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkuID {
            get {
                return this.SkuIDField;
            }
            set {
                if ((this.SkuIDField.Equals(value) != true)) {
                    this.SkuIDField = value;
                    this.RaisePropertyChanged("SkuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkuName {
            get {
                return this.SkuNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuNameField, value) != true)) {
                    this.SkuNameField = value;
                    this.RaisePropertyChanged("SkuName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spare {
            get {
                return this.SpareField;
            }
            set {
                if ((object.ReferenceEquals(this.SpareField, value) != true)) {
                    this.SpareField = value;
                    this.RaisePropertyChanged("Spare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecName {
            get {
                return this.SpecNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecNameField, value) != true)) {
                    this.SpecNameField = value;
                    this.RaisePropertyChanged("SpecName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdjustQuery", Namespace="http://schemas.datacontract.org/2004/07/CMST.Storage.Server.Data.SpecialBusiness")]
    [System.SerializableAttribute()]
    public partial class AdjustQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> AdjustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CmstIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AdjustID {
            get {
                return this.AdjustIDField;
            }
            set {
                if ((this.AdjustIDField.Equals(value) != true)) {
                    this.AdjustIDField = value;
                    this.RaisePropertyChanged("AdjustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmstID {
            get {
                return this.CmstIDField;
            }
            set {
                if ((this.CmstIDField.Equals(value) != true)) {
                    this.CmstIDField = value;
                    this.RaisePropertyChanged("CmstID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepID {
            get {
                return this.DepIDField;
            }
            set {
                if ((this.DepIDField.Equals(value) != true)) {
                    this.DepIDField = value;
                    this.RaisePropertyChanged("DepID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GalName {
            get {
                return this.GalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GalNameField, value) != true)) {
                    this.GalNameField = value;
                    this.RaisePropertyChanged("GalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsName {
            get {
                return this.GoodsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsNameField, value) != true)) {
                    this.GoodsNameField = value;
                    this.RaisePropertyChanged("GoodsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeName {
            get {
                return this.GradeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeNameField, value) != true)) {
                    this.GradeNameField = value;
                    this.RaisePropertyChanged("GradeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManName {
            get {
                return this.ManNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManNameField, value) != true)) {
                    this.ManNameField = value;
                    this.RaisePropertyChanged("ManName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageName {
            get {
                return this.PackageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageNameField, value) != true)) {
                    this.PackageNameField = value;
                    this.RaisePropertyChanged("PackageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Requester {
            get {
                return this.RequesterField;
            }
            set {
                if ((this.RequesterField.Equals(value) != true)) {
                    this.RequesterField = value;
                    this.RaisePropertyChanged("Requester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecName {
            get {
                return this.SpecNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecNameField, value) != true)) {
                    this.SpecNameField = value;
                    this.RaisePropertyChanged("SpecName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeType {
            get {
                return this.TimeTypeField;
            }
            set {
                if ((this.TimeTypeField.Equals(value) != true)) {
                    this.TimeTypeField = value;
                    this.RaisePropertyChanged("TimeType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdjustManageProxy.IAdjustManageProxy")]
    public interface IAdjustManageProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/SaveAdjustTemporary", ReplyAction="http://tempuri.org/IAdjustManage/SaveAdjustTemporaryResponse")]
        string SaveAdjustTemporary(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/SaveAdjustTemporary", ReplyAction="http://tempuri.org/IAdjustManage/SaveAdjustTemporaryResponse")]
        System.Threading.Tasks.Task<string> SaveAdjustTemporaryAsync(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/JavaSaveAdjustTemporary", ReplyAction="http://tempuri.org/IAdjustManage/JavaSaveAdjustTemporaryResponse")]
        string JavaSaveAdjustTemporary(string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/JavaSaveAdjustTemporary", ReplyAction="http://tempuri.org/IAdjustManage/JavaSaveAdjustTemporaryResponse")]
        System.Threading.Tasks.Task<string> JavaSaveAdjustTemporaryAsync(string a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/SaveCheck", ReplyAction="http://tempuri.org/IAdjustManage/SaveCheckResponse")]
        string SaveCheck(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/SaveCheck", ReplyAction="http://tempuri.org/IAdjustManage/SaveCheckResponse")]
        System.Threading.Tasks.Task<string> SaveCheckAsync(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/QueryAdjust", ReplyAction="http://tempuri.org/IAdjustManage/QueryAdjustResponse")]
        string QueryAdjust(long aduId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/QueryAdjust", ReplyAction="http://tempuri.org/IAdjustManage/QueryAdjustResponse")]
        System.Threading.Tasks.Task<string> QueryAdjustAsync(long aduId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/QueryAdjustPageInfo", ReplyAction="http://tempuri.org/IAdjustManage/QueryAdjustPageInfoResponse")]
        string QueryAdjustPageInfo(CMST.Storage.Client.Proxy.AdjustManageProxy.AdjustQuery aq, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/QueryAdjustPageInfo", ReplyAction="http://tempuri.org/IAdjustManage/QueryAdjustPageInfoResponse")]
        System.Threading.Tasks.Task<string> QueryAdjustPageInfoAsync(CMST.Storage.Client.Proxy.AdjustManageProxy.AdjustQuery aq, string queryFields, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/SaveInvalidAdjust", ReplyAction="http://tempuri.org/IAdjustManage/SaveInvalidAdjustResponse")]
        string SaveInvalidAdjust(long id, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdjustManage/SaveInvalidAdjust", ReplyAction="http://tempuri.org/IAdjustManage/SaveInvalidAdjustResponse")]
        System.Threading.Tasks.Task<string> SaveInvalidAdjustAsync(long id, int operatorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdjustManageProxyChannel : CMST.Storage.Client.Proxy.AdjustManageProxy.IAdjustManageProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdjustManageProxyClient : System.ServiceModel.ClientBase<CMST.Storage.Client.Proxy.AdjustManageProxy.IAdjustManageProxy>, CMST.Storage.Client.Proxy.AdjustManageProxy.IAdjustManageProxy {
        
        public AdjustManageProxyClient() {
        }
        
        public AdjustManageProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdjustManageProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdjustManageProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdjustManageProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveAdjustTemporary(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a) {
            return base.Channel.SaveAdjustTemporary(a);
        }
        
        public System.Threading.Tasks.Task<string> SaveAdjustTemporaryAsync(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a) {
            return base.Channel.SaveAdjustTemporaryAsync(a);
        }
        
        public string JavaSaveAdjustTemporary(string a) {
            return base.Channel.JavaSaveAdjustTemporary(a);
        }
        
        public System.Threading.Tasks.Task<string> JavaSaveAdjustTemporaryAsync(string a) {
            return base.Channel.JavaSaveAdjustTemporaryAsync(a);
        }
        
        public string SaveCheck(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a) {
            return base.Channel.SaveCheck(a);
        }
        
        public System.Threading.Tasks.Task<string> SaveCheckAsync(CMST.Storage.Client.Proxy.AdjustManageProxy.Adjust a) {
            return base.Channel.SaveCheckAsync(a);
        }
        
        public string QueryAdjust(long aduId) {
            return base.Channel.QueryAdjust(aduId);
        }
        
        public System.Threading.Tasks.Task<string> QueryAdjustAsync(long aduId) {
            return base.Channel.QueryAdjustAsync(aduId);
        }
        
        public string QueryAdjustPageInfo(CMST.Storage.Client.Proxy.AdjustManageProxy.AdjustQuery aq, string queryFields, int page, int pageSize) {
            return base.Channel.QueryAdjustPageInfo(aq, queryFields, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<string> QueryAdjustPageInfoAsync(CMST.Storage.Client.Proxy.AdjustManageProxy.AdjustQuery aq, string queryFields, int page, int pageSize) {
            return base.Channel.QueryAdjustPageInfoAsync(aq, queryFields, page, pageSize);
        }
        
        public string SaveInvalidAdjust(long id, int operatorId) {
            return base.Channel.SaveInvalidAdjust(id, operatorId);
        }
        
        public System.Threading.Tasks.Task<string> SaveInvalidAdjustAsync(long id, int operatorId) {
            return base.Channel.SaveInvalidAdjustAsync(id, operatorId);
        }
    }
}
